[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "cloudmersive.security"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Vendor/Cloudmersive", "Area/Security & Identity", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-cloudmersive.security"

[build-options]
observabilityIncluded = true
