// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The security APIs help you detect and block security threats.
public isolated client class Client {
    final http:Client clientEp;
    final readonly & ApiKeysConfig apiKeyConfig;
    # Gets invoked to initialize the `connector`.
    #
    # + apiKeyConfig - API keys for authorization 
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ApiKeysConfig apiKeyConfig, ConnectionConfig config =  {}, string serviceUrl = "https://api.cloudmersive.com/security/threat-detection") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
        self.apiKeyConfig = apiKeyConfig.cloneReadOnly();
    }

    # Automatically detect threats in an input string
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - Result of automatic threat detection on the input string 
    remote isolated function detectThreats(string payload, map<string|string[]> headers = {}) returns AutomaticThreatDetectionResult|error {
        string resourcePath = string `/content/automatic/detect/string`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Detect Insecure Deserialization JSON (JID) attacks in a string
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - Result of the insecure deserialization JSON check 
    remote isolated function detectInsecureDeserialization(string payload, map<string|string[]> headers = {}) returns InsecureDeserializationResult|error {
        string resourcePath = string `/content/insecure-deserialization/json/detect/string`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check text input for SQL Injection (SQLI) attacks
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - Result of the SQL injection check 
    remote isolated function checkSqlInjection(string payload, map<string|string[]> headers = {}) returns SqlInjectionResult|error {
        string resourcePath = string `/content/sql-injection/detect/string`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Protect text input from Cross-Site-Scripting (XSS) attacks through normalization
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - Result of the XSS protection, including the normalized text 
    remote isolated function protectXss(string payload, map<string|string[]> headers = {}) returns XssProtectionResult|error {
        string resourcePath = string `/content/xss/detect/string`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Protect text input from XML External Entity (XXE) attacks
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - Result of the XXE threat check 
    remote isolated function checkXxe(string payload, map<string|string[]> headers = {}) returns XxeDetectionResult|error {
        string resourcePath = string `/content/xxe/detect/xml/string`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check a URL for Server-side Request Forgery (SSRF) threats
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input URL request 
    # + return - Result of the SSRF threat check on the URL 
    remote isolated function detectSsrf(SsrfDetectionRequest payload, map<string|string[]> headers = {}) returns SsrfDetectionResponse|error {
        string resourcePath = string `/network/url/ssrf/detect`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check if IP address is a known threat
    #
    # + headers - Headers to be sent with the request 
    # + payload - IP address to check, e.g. "55.55.55.55".  The input is a string so be sure to enclose it in double-quotes 
    # + return - Result of the known-threat check on the IP address 
    remote isolated function checkIpThreat(string payload, map<string|string[]> headers = {}) returns IpThreatResponse|error {
        string resourcePath = string `/network/ip/is-threat`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check if IP address is a Bot client threat
    #
    # + headers - Headers to be sent with the request 
    # + payload - IP address to check, e.g. "55.55.55.55".  The input is a string so be sure to enclose it in double-quotes 
    # + return - Result of the bot check on the IP address 
    remote isolated function checkIpBot(string payload, map<string|string[]> headers = {}) returns BotCheckResponse|error {
        string resourcePath = string `/network/ip/is-bot`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check if IP address is a Tor node server
    #
    # + headers - Headers to be sent with the request 
    # + payload - IP address to check, e.g. "55.55.55.55".  The input is a string so be sure to enclose it in double-quotes 
    # + return - Result of the Tor exit node check on the IP address 
    remote isolated function checkIpTorNode(string payload, map<string|string[]> headers = {}) returns TorNodeCheckResponse|error {
        string resourcePath = string `/network/ip/is-tor-node`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }
}
