// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# Result of performing an XSS protection operation
public type XssProtectionResult record {
    # Normalized string result, with XSS removed
    @jsondata:Name {value: "NormalizedResult"}
    string normalizedResult?;
    # True if the input contained XSS scripting, false otherwise
    @jsondata:Name {value: "ContainedXss"}
    boolean containedXss?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Original input string
    @jsondata:Name {value: "OriginalInput"}
    string originalInput?;
};

# Result of performing an XXE threat detection operation
public type XxeDetectionResult record {
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # True if the input contained XXE threats, false otherwise
    @jsondata:Name {value: "ContainedXxe"}
    boolean containedXxe?;
};

# Result of performing an Insecure Deserialization JSON protection operation
public type AutomaticThreatDetectionResult record {
    # True if the input contained SQL Injection attack, false otherwise
    @jsondata:Name {value: "ContainedSqlInjectionThreat"}
    boolean containedSqlInjectionThreat?;
    # True if the input contained an Server-Side Request Forgery (SSRF) URL attack, false otherwise
    @jsondata:Name {value: "ContainedSsrfThreat"}
    boolean containedSsrfThreat?;
    # True if the input string is XML, false otherwise
    @jsondata:Name {value: "IsXML"}
    boolean isXML?;
    # True if the input contained XXE attack, false otherwise
    @jsondata:Name {value: "ContainedXxeThreat"}
    boolean containedXxeThreat?;
    # True if the input contained Insecure Deserialization JSON, false otherwise
    @jsondata:Name {value: "ContainedJsonInsecureDeserializationAttack"}
    boolean containedJsonInsecureDeserializationAttack?;
    # True if the input contained XSS attack, false otherwise
    @jsondata:Name {value: "ContainedXssThreat"}
    boolean containedXssThreat?;
    # True if the input string is JSON, false otherwise
    @jsondata:Name {value: "IsJSON"}
    boolean isJSON?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # True if the input contained no detected threats, false otherwise
    @jsondata:Name {value: "CleanResult"}
    boolean cleanResult?;
    # Original input string
    @jsondata:Name {value: "OriginalInput"}
    string originalInput?;
    # True if the input string is a URL, false otherwise
    @jsondata:Name {value: "IsURL"}
    boolean isURL?;
};

# Result of performing a Bot check on an IP address
public type BotCheckResponse record {
    # True if the input IP address is a Bot or Robot, false otherwise
    @jsondata:Name {value: "IsBot"}
    boolean isBot?;
};

# Result of performing an SQL Injection protection operation
public type SqlInjectionResult record {
    # True if the input contained SQL Injection attacks, false otherwise
    @jsondata:Name {value: "ContainedSqlInjectionAttack"}
    boolean containedSqlInjectionAttack?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Original input string
    @jsondata:Name {value: "OriginalInput"}
    string originalInput?;
};

# Result of performing a IP threat check on an IP address
public type IpThreatResponse record {
    # Specifies the type of IP threat; possible values include Blocklist, Botnet, WebBot
    @jsondata:Name {value: "ThreatType"}
    string threatType?;
    # True if the input IP address is a threat, false otherwise
    @jsondata:Name {value: "IsThreat"}
    boolean isThreat?;
};

# Result of performing an Insecure Deserialization JSON protection operation
public type InsecureDeserializationResult record {
    # True if the input contained Insecure Deserialization JSON, false otherwise
    @jsondata:Name {value: "ContainedJsonInsecureDeserializationAttack"}
    boolean containedJsonInsecureDeserializationAttack?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Original input string
    @jsondata:Name {value: "OriginalInput"}
    string originalInput?;
};

# Result of checking a URL for SSRF threats
public type SsrfDetectionResponse record {
    # Threat level of the URL; possible values are High, Medium, Low and None
    @jsondata:Name {value: "ThreatLevel"}
    string threatLevel?;
    # True if the URL is clean, false if it is at risk of containing an SSRF threat or attack
    @jsondata:Name {value: "CleanURL"}
    boolean cleanURL?;
};

# Result of performing a Tor node check on an IP address
public type TorNodeCheckResponse record {
    # True if the input IP address is a Tor exit node, false otherwise
    @jsondata:Name {value: "IsTorNode"}
    boolean isTorNode?;
};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    # API Key Authentication
    @display {label: "", kind: "password"}
    string apikey;
|};

# Request to determine if a URL is an SSRF threat check
public type SsrfDetectionRequest record {
    # Top level domains that you do not want to allow access to, e.g. mydomain.com - will block all subdomains as well
    @jsondata:Name {value: "BlockedDomains"}
    string[] blockedDomains?;
    # Set to true to allow CID: schemes for inline content in emails; set to false otherwise.  Default is false
    @jsondata:Name {value: "AllowCidScheme"}
    boolean allowCidScheme?;
    # URL to validate
    @jsondata:Name {value: "URL"}
    string uRL?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
